const fs = require('fs');

// ─── MATEMÁTICAS ─────────────────────────────────────────────────────────────
{
  const path = 'rag_api/knowledge_base/matematicas.json';
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  const nuevas = [
    // GRADO 3
    {id:'mat_g3_073',grado:3,tema:'polígonos',pregunta:'¿Qué es un polígono y cuáles hay?',respuesta:'Un polígono es una figura plana cerrada formada por líneas rectas llamadas lados. Según el número de lados: triángulo (3 lados), cuadrado o rectángulo (4 lados), pentágono (5 lados), hexágono (6 lados). Los reconoces en la vida diaria en señales de tráfico, ventanas y baldosas.',palabras_clave:['polígono','triángulo','cuadrado','rectángulo','pentágono','hexágono','lados','figura plana']},
    {id:'mat_g3_074',grado:3,tema:'números pares e impares',pregunta:'¿Cómo sé si un número es par o impar?',respuesta:'Un número es PAR si termina en 0, 2, 4, 6 u 8. Ejemplos: 12, 24, 36, 48. Un número es IMPAR si termina en 1, 3, 5, 7 o 9. Ejemplos: 13, 25, 37, 49. Los pares se dividen en dos grupos iguales; en los impares siempre sobra uno.',palabras_clave:['par','impar','número','termina','0','2','4','6','8','1','3','5','7','9','dividir']},
    {id:'mat_g3_075',grado:3,tema:'valor posicional',pregunta:'¿Qué es el valor posicional de un número?',respuesta:'El valor posicional dice cuánto vale cada dígito según su posición. En el número 547: el 5 está en las centenas (vale 500), el 4 está en las decenas (vale 40) y el 7 está en las unidades (vale 7). Entonces 547 = 500 + 40 + 7. Esto se llama forma expandida.',palabras_clave:['valor posicional','unidades','decenas','centenas','dígito','posición','cifra','forma expandida']},
    {id:'mat_g3_076',grado:3,tema:'medida con regla',pregunta:'¿Cómo mido un objeto con una regla?',respuesta:'Para medir con regla: coloca el cero de la regla al inicio del objeto, mantén la regla recta y lee el número donde termina el objeto. La unidad es el centímetro (cm). Ejemplo: si un lápiz va del 0 al 15, mide 15 cm. Recuerda: 10 mm = 1 cm y 100 cm = 1 metro.',palabras_clave:['medir','regla','centímetro','cm','milímetro','mm','metro','longitud','tamaño']},
    {id:'mat_g3_077',grado:3,tema:'fracciones propias',pregunta:'¿Qué es una fracción propia?',respuesta:'Una fracción propia es cuando el numerador (número de arriba) es MENOR que el denominador (número de abajo). Ejemplos: 1/4, 2/3, 3/8. Siempre representan menos que un entero. Si partes una naranja en 4 pedazos y te comes 1, comiste 1/4 de la naranja.',palabras_clave:['fracción propia','numerador','denominador','menor','entero','parte','1/4','2/3','3/8']},
    {id:'mat_g3_078',grado:3,tema:'comparar fracciones',pregunta:'¿Cómo comparo dos fracciones con el mismo denominador?',respuesta:'Cuando dos fracciones tienen el mismo denominador, el mayor es el que tiene el numerador más grande. Ejemplo: 3/8 > 2/8 porque 3 > 2. Si el denominador es diferente, convierte al mismo denominador primero. Ejemplo: 1/2 = 4/8, entonces 1/2 > 3/8.',palabras_clave:['comparar','fracciones','denominador','numerador','mayor','menor','igual']},
    {id:'mat_g3_079',grado:3,tema:'gráfica circular',pregunta:'¿Cómo leo una gráfica circular?',respuesta:'Una gráfica circular (o de torta) muestra partes de un todo divididas como sectores de un círculo. Cada color representa una categoría. Si la gráfica muestra que el 50% son niñas y 50% niños, cada mitad del círculo representa un grupo. Todos los sectores siempre suman 100%.',palabras_clave:['gráfica circular','torta','sector','porcentaje','categoría','datos','100%','mitad']},
    {id:'mat_g3_080',grado:3,tema:'problemas de dos pasos',pregunta:'¿Cómo resuelvo un problema que tiene dos operaciones?',respuesta:'Un problema de dos pasos requiere hacer dos operaciones en orden. Lee con atención e identifica qué pide. Ejemplo: Ana tiene 15 caramelos, le dan 8 más y luego regala 6. ¿Cuántos le quedan? Paso 1: 15+8=23. Paso 2: 23-6=17. Le quedan 17 caramelos.',palabras_clave:['problema','dos pasos','operaciones','paso a paso','razonar','leer','solución']},
    {id:'mat_g3_081',grado:3,tema:'tabla del 5',pregunta:'¿Cómo aprendo la tabla del 5?',respuesta:'La tabla del 5 siempre termina en 0 o 5: 5x1=5, 5x2=10, 5x3=15, 5x4=20, 5x5=25, 5x6=30, 5x7=35, 5x8=40, 5x9=45, 5x10=50. Truco: cuenta de 5 en 5. Es tan fácil que si cuentas las manos de todos tus compañeros, usas la tabla del 5.',palabras_clave:['tabla del 5','multiplicar','5','10','15','20','25','30','35','40','45','50']},
    {id:'mat_g3_082',grado:3,tema:'perímetro básico',pregunta:'¿Cómo calculo el perímetro de un rectángulo?',respuesta:'El perímetro es la suma de todos los lados de una figura. En un rectángulo: P = 2 x largo + 2 x ancho. Ejemplo: rectángulo de 6 cm de largo y 4 cm de ancho → P = 2x6 + 2x4 = 12 + 8 = 20 cm. Para el cuadrado: P = 4 x lado.',palabras_clave:['perímetro','rectángulo','lado','largo','ancho','suma','contorno','cuadrado']},

    // GRADO 4
    {id:'mat_g4_067',grado:4,tema:'números primos',pregunta:'¿Qué es un número primo?',respuesta:'Un número primo solo se puede dividir exactamente entre 1 y entre sí mismo. Ejemplos: 2, 3, 5, 7, 11, 13, 17, 19, 23. El número 1 NO es primo. El 4 no es primo porque 4÷2=2. Truco: intenta dividir entre 2, 3, 5... Si ninguno da exacto, es primo.',palabras_clave:['número primo','divisible','divisor','1','2','3','5','7','11','13','17']},
    {id:'mat_g4_068',grado:4,tema:'ángulos tipos',pregunta:'¿Qué diferencia hay entre ángulo agudo, recto y obtuso?',respuesta:'Un ángulo RECTO mide exactamente 90° (como la esquina de un cuaderno). Un ángulo AGUDO mide menos de 90° (como la punta de un triángulo equilátero). Un ángulo OBTUSO mide más de 90° pero menos de 180° (como una puerta entreabierta). El ángulo LLANO mide 180°.',palabras_clave:['ángulo','agudo','recto','obtuso','llano','90','180','grado','esquina']},
    {id:'mat_g4_069',grado:4,tema:'fracciones equivalentes avanzado',pregunta:'¿Cómo sé si dos fracciones son equivalentes?',respuesta:'Dos fracciones son equivalentes si representan la misma parte. Método 1: multiplica en cruz y compara. Ejemplo: 2/3 y 4/6 → 2x6=12 y 3x4=12, son iguales. Método 2: simplifica ambas a su forma irreducible. 4/6 ÷ 2 = 2/3. Son equivalentes.',palabras_clave:['equivalentes','fracciones','multiplicación cruzada','simplificar','irreducible','igual']},
    {id:'mat_g4_070',grado:4,tema:'propiedad asociativa',pregunta:'¿Qué es la propiedad asociativa?',respuesta:'La propiedad asociativa dice que puedes agrupar los números de diferente forma y el resultado es el mismo. Suma: (2+3)+4 = 2+(3+4) → 9 = 9. Multiplicación: (2x3)x4 = 2x(3x4) → 24 = 24. Esto te permite escoger el orden que más te convenga para calcular más rápido.',palabras_clave:['asociativa','propiedad','suma','multiplicación','agrupar','paréntesis','orden']},
    {id:'mat_g4_071',grado:4,tema:'área del triángulo',pregunta:'¿Cómo calculo el área de un triángulo?',respuesta:'El área de un triángulo se calcula con: Área = (base × altura) ÷ 2. La base es el lado inferior y la altura es la línea perpendicular hasta el vértice opuesto. Ejemplo: base=8 cm, altura=5 cm → Área = (8x5)÷2 = 40÷2 = 20 cm². La unidad de área siempre es cuadrada.',palabras_clave:['área','triángulo','base','altura','fórmula','dividir','2','cm cuadrado','perpendicular']},
    {id:'mat_g4_072',grado:4,tema:'porcentajes básicos',pregunta:'¿Qué es un porcentaje y cómo calculo el 50%, 25% y 10%?',respuesta:'Un porcentaje es una parte de cada 100 (símbolo %). El 50% = mitad (divide entre 2). El 25% = un cuarto (divide entre 4). El 10% = divide entre 10. Ejemplo: 50% de 80 = 40. 25% de 80 = 20. 10% de 80 = 8. Truco: 30% = 3 × 10%.',palabras_clave:['porcentaje','%','50','25','10','100','mitad','cuarto','calcular','dividir']},
    {id:'mat_g4_073',grado:4,tema:'múltiplos y divisores',pregunta:'¿Cuál es la diferencia entre múltiplos y divisores?',respuesta:'Los MÚLTIPLOS de un número son los resultados de multiplicarlo: múltiplos de 4 son 4,8,12,16,20... Los DIVISORES son los números que lo dividen exactamente: divisores de 12 son 1,2,3,4,6,12 (todos dividen 12 sin residuo). Los divisores son menores o iguales al número.',palabras_clave:['múltiplo','divisor','multiplicar','dividir','exacto','residuo','número']},
    {id:'mat_g4_074',grado:4,tema:'división de tres cifras',pregunta:'¿Cómo divido un número de tres cifras entre uno de una cifra?',respuesta:'Ejemplo: 648 ÷ 3. Paso 1: divide la primera cifra: 6÷3=2. Paso 2: baja el 4 → 04÷3=1 (resto 1). Paso 3: baja el 8 → 18÷3=6. Resultado: 216. Verificación: 216×3=648. Si la primera cifra es menor que el divisor, toma las dos primeras cifras juntas.',palabras_clave:['dividir','tres cifras','cociente','residuo','verificación','paso a paso','cifra']},
    {id:'mat_g4_075',grado:4,tema:'probabilidad simple',pregunta:'¿Qué es la probabilidad y cómo se calcula?',respuesta:'La probabilidad mide qué tan probable es un evento. Se calcula: probabilidad = casos favorables ÷ casos totales. Ejemplo: un dado tiene 6 caras. Probabilidad de sacar 3 = 1/6. Probabilidad de sacar número par (2,4,6) = 3/6 = 1/2. Va de 0 (imposible) a 1 (seguro).',palabras_clave:['probabilidad','evento','posible','fracción','dado','favorable','total','seguro','imposible']},
    {id:'mat_g4_076',grado:4,tema:'ecuaciones sencillas',pregunta:'¿Cómo resuelvo una ecuación simple con una incógnita?',respuesta:'Una ecuación tiene una incógnita (letra) que debes encontrar. Regla: lo que haces a un lado, lo haces al otro. Ejemplo 1: x + 5 = 12 → x = 12 - 5 = 7. Ejemplo 2: 3x = 18 → x = 18÷3 = 6. Siempre verifica: sustituye x y comprueba que la igualdad se cumple.',palabras_clave:['ecuación','incógnita','x','despejar','resolver','verificar','igual','lado']},

    // GRADO 5
    {id:'mat_g5_071',grado:5,tema:'operaciones con enteros',pregunta:'¿Cómo sumo y resto números enteros negativos?',respuesta:'Reglas para sumar enteros: mismo signo → suma los valores y conserva el signo. Diferente signo → resta el menor del mayor y usa el signo del número mayor en valor absoluto. Ejemplos: (-5)+(-3)=-8. (-5)+3=-(5-3)=-2. (+4)+(-7)=-(7-4)=-3.',palabras_clave:['negativo','entero','suma','resta','signo','recta numérica','positivo','valor absoluto']},
    {id:'mat_g5_072',grado:5,tema:'MCD',pregunta:'¿Qué es el MCD y cómo lo calculo?',respuesta:'El Máximo Común Divisor (MCD) es el número más grande que divide exactamente a dos o más números. Método: descompón en factores primos y toma los comunes con el menor exponente. Ejemplo: MCD(12,18) → 12=2²×3, 18=2×3² → MCD=2×3=6. Sirve para simplificar fracciones.',palabras_clave:['MCD','máximo común divisor','factor primo','descomponer','común','simplificar','exponente']},
    {id:'mat_g5_073',grado:5,tema:'multiplicación de fracciones',pregunta:'¿Cómo multiplico dos fracciones?',respuesta:'Para multiplicar fracciones: multiplica numerador con numerador y denominador con denominador. Ejemplo: 2/3 × 3/4 = (2×3)/(3×4) = 6/12 = 1/2. No necesitas igual denominador. Truco: antes de multiplicar, simplifica en forma cruzada para obtener números más pequeños.',palabras_clave:['multiplicar','fracciones','numerador','denominador','simplificar','cruzado','resultado']},
    {id:'mat_g5_074',grado:5,tema:'expresiones algebraicas',pregunta:'¿Qué es una expresión algebraica y cómo la evalúo?',respuesta:'Una expresión algebraica combina números, variables (letras) y operaciones. Ejemplo: 3x+5. Si x=2 entonces 3(2)+5=11. Para evaluar, sustituye la variable por el valor dado. Términos semejantes (misma variable) sí se suman: 2x+3x=5x. Distintos no: 2x+3y queda igual.',palabras_clave:['expresión algebraica','variable','término','coeficiente','semejante','evaluar','sustituir']},
    {id:'mat_g5_075',grado:5,tema:'media aritmética',pregunta:'¿Cómo calculo la media aritmética (promedio)?',respuesta:'La media aritmética se calcula sumando todos los valores y dividiendo entre cuántos hay. Ejemplo: notas de 5 estudiantes: 8,7,9,6,10 → suma=40 → media=40÷5=8. El promedio representa el valor central típico del conjunto. Se usa en calificaciones, temperaturas y estadísticas.',palabras_clave:['media','promedio','aritmética','sumar','dividir','datos','valor','calificaciones','estadística']},
    {id:'mat_g5_076',grado:5,tema:'volumen de prismas',pregunta:'¿Cómo calculo el volumen de un cubo y un prisma rectangular?',respuesta:'El volumen mide el espacio interior. Cubo: V = lado³. Ejemplo: lado=4 cm → V=4×4×4=64 cm³. Prisma rectangular: V = largo × ancho × alto. Ejemplo: 5×3×2=30 cm³. El volumen se mide en unidades cúbicas (cm³, m³). Una caja de leche de 1 litro tiene 1000 cm³.',palabras_clave:['volumen','cubo','prisma','largo','ancho','alto','cm cúbico','espacio','litro']},
    {id:'mat_g5_077',grado:5,tema:'regla de tres directa',pregunta:'¿Cómo resuelvo una regla de tres simple directa?',respuesta:'La regla de tres directa resuelve proporciones: si una cantidad aumenta, la otra también. Formato: A → B y C → X. Fórmula: X = (B × C) ÷ A. Ejemplo: si 3 cuadernos cuestan $9.000, ¿cuánto cuestan 5 cuadernos? X = (9000×5)÷3 = 45000÷3 = $15.000.',palabras_clave:['regla de tres','proporción','directa','precio','cantidad','calcular','cuadernos']},
    {id:'mat_g5_078',grado:5,tema:'números irracionales',pregunta:'¿Qué son los números irracionales?',respuesta:'Los números irracionales no se pueden escribir como fracción exacta y sus decimales son infinitos sin patrón que se repita. El más famoso es π (pi) ≈ 3.14159... y la raíz de 2 (√2) ≈ 1.41421... Se usan en geometría para calcular circunferencias y diagonales.',palabras_clave:['irracional','pi','raíz cuadrada','decimal','infinito','fracción','pi 3.14','√2']},
    {id:'mat_g5_079',grado:5,tema:'plano cartesiano avanzado',pregunta:'¿Cómo grafico una función sencilla en el plano cartesiano?',respuesta:'Para graficar y=2x: crea una tabla: si x=0, y=0; x=1, y=2; x=2, y=4; x=-1, y=-2. Ubica cada par ordenado (x,y) en el plano y únelos con una línea. Esa línea recta es la gráfica de la función. El eje horizontal es X y el vertical es Y.',palabras_clave:['plano cartesiano','función','graficar','tabla de valores','par ordenado','eje x','eje y','recta']},
    {id:'mat_g5_080',grado:5,tema:'teorema de Pitágoras',pregunta:'¿Qué es el teorema de Pitágoras y cómo lo aplico?',respuesta:'En un triángulo rectángulo: hipotenusa² = cateto1² + cateto2². La hipotenusa es el lado más largo (frente al ángulo recto). Ejemplo clásico: catetos 3 y 4 → hipotenusa² = 9+16 = 25 → hipotenusa = √25 = 5 cm. Se usa para medir distancias sin medir directamente.',palabras_clave:['Pitágoras','triángulo rectángulo','hipotenusa','cateto','cuadrado','raíz','3-4-5','distancia']}
  ];
  data.contenido.push(...nuevas);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log('matematicas.json OK. Total:', data.contenido.length);
}

// ─── ESPAÑOL ─────────────────────────────────────────────────────────────────
{
  const path = 'rag_api/knowledge_base/espanol.json';
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  const nuevas = [
    // GRADO 3
    {id:'esp_g3_037',grado:3,tema:'uso del acento',pregunta:'¿Qué es el acento ortográfico (tilde) y cuándo se usa?',respuesta:'El acento ortográfico o tilde es una rayita (´) que se coloca sobre una vocal para indicar que esa sílaba se pronuncia más fuerte. Palabras agudas llevan tilde si terminan en n, s o vocal (corazón, café). Graves llevan tilde si NO terminan en n, s o vocal (árbol, lápiz). Esdrújulas siempre llevan tilde (pájaro, médico).',palabras_clave:['acento','tilde','ortografía','aguda','grave','esdrújula','sílaba','vocal','pronunciar']},
    {id:'esp_g3_038',grado:3,tema:'sustantivos tipos',pregunta:'¿Cuáles son los tipos de sustantivos?',respuesta:'Los sustantivos son palabras que nombran personas, animales, lugares o cosas. Tipos: PROPIOS nombran algo específico y se escriben con mayúscula (Colombia, Juan, Medellín). COMUNES nombran en general (ciudad, niño, perro). CONCRETOS se pueden tocar (mesa, pelota). ABSTRACTOS no se tocan (amor, libertad, miedo).',palabras_clave:['sustantivo','propio','común','concreto','abstracto','mayúscula','nombrar','persona','lugar']},
    {id:'esp_g3_039',grado:3,tema:'adjetivos',pregunta:'¿Qué es un adjetivo calificativo y cómo lo uso?',respuesta:'El adjetivo calificativo es la palabra que describe o da características al sustantivo. Ejemplos: pelota ROJA, niño INTELIGENTE, casa GRANDE. El adjetivo concuerda en género y número con el sustantivo: un perro NEGRO / una perra NEGRA / unos perros NEGROS. Siempre acompaña al sustantivo.',palabras_clave:['adjetivo','calificativo','describir','característica','género','número','concordancia','sustantivo']},
    {id:'esp_g3_040',grado:3,tema:'verbos tiempos',pregunta:'¿Cómo identifico si un verbo está en pasado, presente o futuro?',respuesta:'Los verbos cambian según el tiempo. PASADO: la acción ya ocurrió (comí, jugué, estudié). PRESENTE: la acción ocurre ahora (como, juego, estudio). FUTURO: la acción va a ocurrir (comeré, jugaré, estudiaré). Truco: pregúntate cuándo pasa la acción: ¿antes, ahora o después?',palabras_clave:['verbo','pasado','presente','futuro','tiempo','acción','conjugar','antes','ahora','después']},
    {id:'esp_g3_041',grado:3,tema:'el cuento',pregunta:'¿Cuáles son las partes de un cuento?',respuesta:'Un cuento tiene tres partes: INICIO (presentación de los personajes y el lugar donde ocurre la historia), NUDO (el problema o conflicto que viven los personajes, la parte más emocionante) y DESENLACE (la solución del problema y el final de la historia). Todo cuento tiene personajes principales y secundarios.',palabras_clave:['cuento','inicio','nudo','desenlace','personaje','problema','solución','historia','narrativo']},
    {id:'esp_g3_042',grado:3,tema:'texto descriptivo',pregunta:'¿Qué es un texto descriptivo y cómo se escribe?',respuesta:'Un texto descriptivo explica cómo es algo: su forma, color, tamaño, textura, olor. Se usa para describir personas, animales, lugares u objetos. Usa muchos adjetivos. Ejemplo: "El gato es pequeño, de pelo negro y brillante, con ojos verdes y una cola larga y esponjosa." Responde a la pregunta: ¿Cómo es?',palabras_clave:['descriptivo','describir','adjetivo','forma','color','tamaño','textura','características','texto']},
    {id:'esp_g3_043',grado:3,tema:'signos de puntuación',pregunta:'¿Para qué sirven el punto, la coma y los signos de interrogación?',respuesta:'El PUNTO (.) indica el final de una oración. La COMA (,) separa elementos de una lista o hace una pausa corta. Los signos de INTERROGACIÓN (¿?) van al inicio y al final de una pregunta. Los de EXCLAMACIÓN (¡!) expresan emoción o sorpresa. Usarlos bien hace el texto más claro.',palabras_clave:['punto','coma','interrogación','exclamación','signo de puntuación','oración','pausa','pregunta']},
    {id:'esp_g3_044',grado:3,tema:'sinónimos grado 3',pregunta:'¿Qué son los sinónimos y para qué los uso?',respuesta:'Los sinónimos son palabras que tienen un significado igual o muy parecido. Ejemplos: bonito/hermoso/lindo, rápido/veloz/ágil, triste/melancólico/afligido. Se usan para no repetir la misma palabra en un texto y hacer la escritura más variada e interesante. Es buena práctica buscarlos en el diccionario.',palabras_clave:['sinónimo','significado','igual','parecido','vocabulario','diccionario','variedad','repetir']},
    {id:'esp_g3_045',grado:3,tema:'párrafo',pregunta:'¿Qué es un párrafo y cómo lo escribo bien?',respuesta:'Un párrafo es un conjunto de oraciones relacionadas que desarrollan una misma idea. Comienza con sangría (espacio al inicio) o línea en blanco. Tiene: oración principal (la idea más importante) y oraciones de apoyo (explican o dan ejemplos). Un párrafo tiene mínimo 3 oraciones y habla de un solo tema.',palabras_clave:['párrafo','oración','idea','sangría','principal','apoyo','tema','escribir']},
    {id:'esp_g3_046',grado:3,tema:'diálogo',pregunta:'¿Cómo se escribe un diálogo en un cuento?',respuesta:'El diálogo es la conversación entre personajes. Se escribe con guion largo (—) al inicio de cada intervención. Ejemplo: — ¿A dónde vas? — preguntó Juan. — Voy al parque — respondió María. Las palabras del narrador (dijo, preguntó, respondió) van separadas del diálogo. Los signos de puntuación van dentro.',palabras_clave:['diálogo','guion','conversación','personaje','narrador','dijo','preguntó','respondió']},

    // GRADO 4
    {id:'esp_g4_028',grado:4,tema:'conectores textuales',pregunta:'¿Qué son los conectores textuales y cuáles son los más usados?',respuesta:'Los conectores son palabras o frases que unen oraciones y párrafos para que el texto fluya con sentido. De adición: además, también, igualmente. De contraste: pero, sin embargo, aunque. De causa: porque, ya que, debido a. De consecuencia: por lo tanto, entonces, así que. De secuencia: primero, luego, finalmente.',palabras_clave:['conector','textual','además','pero','porque','sin embargo','por lo tanto','primero','luego','finalmente']},
    {id:'esp_g4_029',grado:4,tema:'la noticia',pregunta:'¿Qué es una noticia y qué partes tiene?',respuesta:'La noticia informa sobre un hecho real y reciente. Sus partes son: TITULAR (título llamativo que resume el evento), SUBTÍTULO (complementa el titular), ENTRADILLA (primer párrafo con lo más importante: qué, quién, cuándo, dónde, por qué y cómo) y CUERPO (detalles y contexto del hecho). Debe ser objetiva y veraz.',palabras_clave:['noticia','titular','subtítulo','entradilla','cuerpo','hecho','real','informar','periodismo']},
    {id:'esp_g4_030',grado:4,tema:'carta formal e informal',pregunta:'¿Qué diferencia hay entre una carta formal y una informal?',respuesta:'La carta FORMAL se escribe a una institución, empresa o persona desconocida. Usa lenguaje respetuoso y estructura fija: encabezado, saludo formal (Estimado señor/a), cuerpo, despedida (Atentamente) y firma. La INFORMAL es para amigos o familia: lenguaje cercano, saludo afectuoso (Querido amigo) y despedida cariñosa.',palabras_clave:['carta','formal','informal','encabezado','saludo','despedida','lenguaje','respetuoso','amigo']},
    {id:'esp_g4_031',grado:4,tema:'discurso directo e indirecto',pregunta:'¿Cuál es la diferencia entre el discurso directo e indirecto?',respuesta:'El DISCURSO DIRECTO reproduce exactamente las palabras del hablante con comillas o guion: Juan dijo: "Tengo hambre." El DISCURSO INDIRECTO las reporta sin comillas, cambiando pronombres y tiempos verbales: Juan dijo que tenía hambre. El indirecto integra las palabras al relato del narrador.',palabras_clave:['discurso directo','discurso indirecto','comillas','guion','narrador','verbos','reportar','citar']},
    {id:'esp_g4_032',grado:4,tema:'texto argumentativo',pregunta:'¿Qué es un texto argumentativo y cómo se estructura?',respuesta:'El texto argumentativo busca convencer al lector de una postura. Estructura: TESIS (idea principal que se defiende), ARGUMENTOS (razones, datos y ejemplos que apoyan la tesis) y CONCLUSIÓN (reafirma la tesis). Ejemplo: Tesis: el deporte es esencial. Argumento: mejora la salud y la concentración.',palabras_clave:['argumentativo','tesis','argumento','conclusión','convencer','opinar','razón','evidencia','postura']},
    {id:'esp_g4_033',grado:4,tema:'prefijos y sufijos',pregunta:'¿Qué son los prefijos y sufijos en español?',respuesta:'Los PREFIJOS van al inicio de una palabra y cambian su significado: in- (imposible), des- (desorden), re- (rehacer), pre- (prehistoria). Los SUFIJOS van al final y cambian el significado o la categoría: -ción (canción), -mente (rápidamente), -ito (gatito, diminutivo), -ísimo (grandísimo, superlativo).',palabras_clave:['prefijo','sufijo','morfema','in','des','re','ción','mente','ito','significado','familia de palabras']},
    {id:'esp_g4_034',grado:4,tema:'oración sujeto predicado',pregunta:'¿Cómo identifico el sujeto y el predicado de una oración?',respuesta:'El SUJETO es quien realiza la acción o de quien se habla. El PREDICADO es lo que se dice del sujeto (incluye el verbo). Ejemplo: "Los estudiantes de grado 4 estudian mucho." Sujeto: Los estudiantes de grado 4. Predicado: estudian mucho. Truco: pregunta ¿quién? o ¿qué? hace la acción para encontrar el sujeto.',palabras_clave:['oración','sujeto','predicado','verbo','acción','quién','identificar','análisis']},
    {id:'esp_g4_035',grado:4,tema:'resumen',pregunta:'¿Cómo hago un buen resumen de un texto?',respuesta:'Para resumir: 1) Lee el texto completo. 2) Identifica las ideas principales (una por párrafo). 3) Elimina ejemplos, repeticiones y detalles secundarios. 4) Escribe las ideas principales con tus propias palabras. 5) Organiza en párrafos coherentes. Un resumen debe ser más corto que el texto original pero mantener su significado.',palabras_clave:['resumen','ideas principales','párrafo','texto','síntesis','releer','organizar','comprensión']},
    {id:'esp_g4_036',grado:4,tema:'mapa conceptual',pregunta:'¿Cómo elaboro un mapa conceptual?',respuesta:'Un mapa conceptual organiza ideas visualmente. Pasos: 1) Escribe el tema central en un óvalo. 2) Anota las ideas principales relacionadas y únelas con líneas. 3) Agrega ideas secundarias a cada principal. 4) Usa palabras de enlace en las líneas (es, tiene, produce, incluye). Ayuda a estudiar y comprender mejor los textos.',palabras_clave:['mapa conceptual','organizar','ideas','óvalo','enlace','visual','esquema','jerarquía']},
    {id:'esp_g4_037',grado:4,tema:'lectura inferencial',pregunta:'¿Qué es una inferencia en la lectura?',respuesta:'Una inferencia es una conclusión que sacas de lo que el texto dice sin decirlo directamente. Ejemplo: si un texto dice "María entró empapada y dejando charcos", puedes inferir que llovía aunque no lo diga. Para inferir: lee entre líneas, relaciona datos y usa tu conocimiento previo. Es la lectura más profunda.',palabras_clave:['inferencia','concluir','leer entre líneas','implícito','texto','comprender','significado','deducir']},

    // GRADO 5
    {id:'esp_g5_028',grado:5,tema:'figuras literarias',pregunta:'¿Qué son las figuras literarias y cuáles son las principales?',respuesta:'Las figuras literarias son recursos del lenguaje que dan belleza y expresividad al texto. Principales: METÁFORA: comparar sin usar "como" (tus ojos son estrellas). SÍMIL: comparar usando "como" (rápido como el viento). PERSONIFICACIÓN: dar cualidades humanas a cosas (el mar llora). HIPÉRBOLE: exageración (te lo he dicho un millón de veces).',palabras_clave:['figura literaria','metáfora','símil','personificación','hipérbole','lenguaje','poético','expresividad']},
    {id:'esp_g5_029',grado:5,tema:'el ensayo',pregunta:'¿Qué es un ensayo y cómo se diferencia del texto argumentativo?',respuesta:'El ensayo es un texto donde el autor expresa sus ideas y reflexiones sobre un tema de forma personal y fundamentada. A diferencia del texto argumentativo puro, el ensayo tiene mayor libertad estilística y puede mezclar argumentación, análisis y opinión. Partes: introducción, desarrollo argumentado y conclusión reflexiva.',palabras_clave:['ensayo','opinión','reflexión','argumentar','personal','introducción','desarrollo','conclusión']},
    {id:'esp_g5_030',grado:5,tema:'el debate',pregunta:'¿Cómo participo en un debate escolar?',respuesta:'En un debate defienden posturas distintas sobre un tema. Para participar bien: 1) Prepara argumentos con datos y ejemplos. 2) Escucha con respeto al otro. 3) Responde con contraargumentos lógicos, no con insultos. 4) Usa conectores de contraste (sin embargo, aunque, por el contrario). 5) Concluye con una síntesis de tu postura.',palabras_clave:['debate','argumento','contraargumento','postura','respeto','escuchar','defender','opinar','lógica']},
    {id:'esp_g5_031',grado:5,tema:'la entrevista',pregunta:'¿Qué es una entrevista y cómo se estructura?',respuesta:'La entrevista es un diálogo con el propósito de obtener información de una persona experta o reconocida. Partes: PRESENTACIÓN del entrevistado, PREGUNTAS del entrevistador (abiertas para respuestas amplias) y RESPUESTAS del entrevistado. Las preguntas buenas comienzan con ¿Por qué?, ¿Cómo?, ¿Qué piensa sobre...?',palabras_clave:['entrevista','entrevistado','entrevistador','pregunta','respuesta','diálogo','información','periodismo']},
    {id:'esp_g5_032',grado:5,tema:'reseña literaria',pregunta:'¿Cómo escribo una reseña de un libro?',respuesta:'Una reseña evalúa y recomienda (o no) un libro. Partes: 1) Datos del libro (título, autor, año). 2) Breve resumen del argumento SIN revelar el final. 3) Análisis de personajes, tema y estilo del autor. 4) Opinión personal fundamentada: ¿Qué te gustó? ¿Qué no? 5) Recomendación. No es solo un resumen, es una evaluación.',palabras_clave:['reseña','libro','autor','argumento','personaje','tema','opinión','recomendar','evaluar']},
    {id:'esp_g5_033',grado:5,tema:'coherencia y cohesión',pregunta:'¿Qué es la coherencia y la cohesión en un texto?',respuesta:'La COHERENCIA hace que el texto tenga sentido y las ideas se relacionen lógicamente (no mezcla temas sin conexión). La COHESIÓN es cómo las oraciones están bien conectadas gramaticalmente (uso de conectores, pronombres y sinónimos para no repetir palabras). Un texto bueno tiene ambas. Coherencia = ideas. Cohesión = forma.',palabras_clave:['coherencia','cohesión','texto','lógica','conector','pronombre','sinónimo','sentido','organización']},
    {id:'esp_g5_034',grado:5,tema:'textos multimodales',pregunta:'¿Qué son los textos multimodales?',respuesta:'Los textos multimodales combinan diferentes modos de comunicación: palabras escritas, imágenes, gráficas, videos, audio o íconos. Ejemplos: una infografía, un afiche publicitario, una página web, un cómic. Para leerlos hay que interpretar tanto el texto escrito como las imágenes y cómo se relacionan entre sí.',palabras_clave:['multimodal','imagen','texto','infografía','afiche','cómic','video','icono','leer','interpretar']},
    {id:'esp_g5_035',grado:5,tema:'comunicación digital',pregunta:'¿Cómo debo comunicarme de forma responsable en medios digitales?',respuesta:'La comunicación digital responsable implica: 1) Verificar la información antes de compartirla (evitar fake news). 2) Usar lenguaje respetuoso en chats y redes. 3) Cuidar la privacidad (no compartir datos personales). 4) Reconocer el ciberacoso y reportarlo. 5) Diferenciar entre fuentes confiables y no confiables.',palabras_clave:['digital','comunicación','responsable','fake news','privacidad','ciberacoso','redes','verificar','fuente']}
  ];
  data.contenido.push(...nuevas);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log('espanol.json OK. Total:', data.contenido.length);
}

// ─── INGLÉS ──────────────────────────────────────────────────────────────────
{
  const path = 'rag_api/knowledge_base/ingles.json';
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  const nuevas = [
    // GRADO 3
    {id:'ing_g3_025',grado:3,tema:'animals and habitats',pregunta:'¿Cómo digo los animales y sus hábitats en inglés?',respuesta:'Animals and their habitats: Fish (pez) lives in the ocean or river (océano o río). Birds (aves) live in forests or trees (bosques o árboles). Bears (osos) live in the forest (bosque). Snakes (serpientes) live in the jungle (selva). Penguins (pingüinos) live in Antarctica. Camels (camellos) live in the desert (desierto).',palabras_clave:['animal','habitat','fish','bird','bear','snake','penguin','camel','ocean','forest','jungle','desert']},
    {id:'ing_g3_026',grado:3,tema:'body parts',pregunta:'¿Cómo se llaman las partes del cuerpo en inglés?',respuesta:'Body parts: head (cabeza), eye (ojo), ear (oreja), nose (nariz), mouth (boca), neck (cuello), shoulder (hombro), arm (brazo), hand (mano), finger (dedo), chest (pecho), stomach (estómago), leg (pierna), knee (rodilla), foot/feet (pie/pies). Plural irregular: foot → feet, tooth → teeth.',palabras_clave:['body','head','eye','ear','nose','mouth','arm','hand','leg','foot','knee','parts']},
    {id:'ing_g3_027',grado:3,tema:'feelings',pregunta:'¿Cómo expreso emociones en inglés?',respuesta:'Feelings and emotions: happy (feliz), sad (triste), angry (enojado), scared (asustado), excited (emocionado), bored (aburrido), tired (cansado), hungry (hambriento), thirsty (sediento), surprised (sorprendido). Pregunta: How do you feel? Respuesta: I feel happy / I am sad. Se usa el verbo "to be" o "to feel".',palabras_clave:['feelings','happy','sad','angry','scared','excited','bored','tired','hungry','how do you feel']},
    {id:'ing_g3_028',grado:3,tema:'family members',pregunta:'¿Cómo se llaman los miembros de la familia en inglés?',respuesta:'Family members: mother/mom (mamá), father/dad (papá), brother (hermano), sister (hermana), grandmother/grandma (abuela), grandfather/grandpa (abuelo), aunt (tía), uncle (tío), cousin (primo/a), son (hijo), daughter (hija). My family = mi familia. This is my mom = Esta es mi mamá.',palabras_clave:['family','mother','father','brother','sister','grandmother','grandfather','aunt','uncle','cousin']},
    {id:'ing_g3_029',grado:3,tema:'school objects',pregunta:'¿Cómo se llaman los objetos del salón de clase en inglés?',respuesta:'Classroom objects: pencil (lápiz), pen (lapicero), ruler (regla), eraser (borrador), notebook (cuaderno), book (libro), backpack (mochila), scissors (tijeras), glue (pegante), crayon (crayón), desk (pupitre), board (tablero), chalk (tiza). I have a pencil in my backpack. = Tengo un lápiz en mi mochila.',palabras_clave:['pencil','pen','ruler','eraser','notebook','book','backpack','scissors','desk','classroom','school']},
    {id:'ing_g3_030',grado:3,tema:'likes and dislikes',pregunta:'¿Cómo digo lo que me gusta y no me gusta en inglés?',respuesta:'Para expresar gustos: I like... (me gusta), I love... (me encanta), I enjoy... (disfruto). Para rechazos: I do not like... (no me gusta), I hate... (odio), I dislike... (me disgusta). Ejemplos: I like pizza. I love football. I do not like vegetables. Do you like music? Yes, I do / No, I do not.',palabras_clave:['like','love','enjoy','do not like','hate','dislike','gustos','preferencias','yes','no']},
    {id:'ing_g3_031',grado:3,tema:'colors and shapes',pregunta:'¿Cómo describo colores y formas en inglés?',respuesta:'Colors: red (rojo), blue (azul), green (verde), yellow (amarillo), orange (naranja), purple (morado), pink (rosado), brown (café), black (negro), white (blanco), gray (gris). Shapes: circle (círculo), square (cuadrado), triangle (triángulo), rectangle (rectángulo), star (estrella). The flag is yellow, blue and red.',palabras_clave:['color','shape','red','blue','green','yellow','circle','square','triangle','rectangle','star']},
    {id:'ing_g3_032',grado:3,tema:'daily actions verbs',pregunta:'¿Cuáles son los verbos de acciones cotidianas en inglés?',respuesta:'Daily action verbs: wake up (despertarse), eat (comer), drink (tomar), walk (caminar), run (correr), jump (saltar), read (leer), write (escribir), draw (dibujar), play (jugar), sleep (dormir), study (estudiar), clean (limpiar), cook (cocinar). En presente simple: I eat breakfast at 7 a.m.',palabras_clave:['verb','wake up','eat','drink','walk','run','jump','read','write','play','sleep','study']},
    {id:'ing_g3_033',grado:3,tema:'seasons weather',pregunta:'¿Cómo hablo del clima y las estaciones en inglés?',respuesta:'Seasons: spring (primavera), summer (verano), fall/autumn (otoño), winter (invierno). Colombia no tiene estaciones, pero sí tiene dry season (verano) y rainy season (invierno). Weather: sunny (soleado), cloudy (nublado), rainy (lluvioso), windy (ventoso), cold (frío), hot (caliente). How is the weather? It is sunny today.',palabras_clave:['season','weather','spring','summer','fall','winter','sunny','cloudy','rainy','windy','cold','hot']},
    {id:'ing_g3_034',grado:3,tema:'numbers advanced g3',pregunta:'¿Cómo digo los números del 100 al 1000 en inglés?',respuesta:'Numbers: 100 = one hundred, 200 = two hundred, 300 = three hundred, 500 = five hundred, 1000 = one thousand. Para números intermedios: 150 = one hundred and fifty, 225 = two hundred and twenty-five. Ordinals: first (1ro), second (2do), third (3ro), fourth (4to), fifth (5to), tenth (10mo).',palabras_clave:['numbers','hundred','thousand','150','225','first','second','third','fourth','fifth','ordinal']},

    // GRADO 4
    {id:'ing_g4_025',grado:4,tema:'countries nationalities',pregunta:'¿Cómo hablo de países y nacionalidades en inglés?',respuesta:'Countries and nationalities: Colombia → Colombian, USA → American, Mexico → Mexican, Brazil → Brazilian, France → French, Germany → German, China → Chinese, Japan → Japanese, Spain → Spanish. Question: Where are you from? I am from Colombia. I am Colombian. Nationalities use capital letters.',palabras_clave:['country','nationality','Colombian','American','Mexican','Brazilian','French','where are you from']},
    {id:'ing_g4_026',grado:4,tema:'quantity expressions',pregunta:'¿Cómo uso some, any, many, much, a lot of?',respuesta:'SOME: para afirmaciones (I have some apples). ANY: para negaciones y preguntas (I do not have any milk / Do you have any books?). MANY: para contables en plural (many books, many students). MUCH: para incontables (much water, much money). A LOT OF: para ambos (a lot of friends / a lot of time).',palabras_clave:['some','any','many','much','a lot of','countable','uncountable','afirmación','negación','pregunta']},
    {id:'ing_g4_027',grado:4,tema:'past continuous',pregunta:'¿Cómo uso el pasado continuo en inglés?',respuesta:'El Past Continuous expresa una acción que estaba ocurriendo en un momento pasado. Forma: sujeto + was/were + verbo-ing. Ejemplos: I was reading when you called (Estaba leyendo cuando llamaste). They were playing football at 4 p.m. (Estaban jugando fútbol a las 4 p.m.). Was/were son el pasado del verbo to be.',palabras_clave:['past continuous','was','were','ing','acción en progreso','pasado','cuando','while','at that time']},
    {id:'ing_g4_028',grado:4,tema:'asking for information',pregunta:'¿Cómo pido y doy información en inglés?',respuesta:'Para pedir información: Can you tell me...? (¿Me puedes decir...?), Could you help me? (¿Podrías ayudarme?), Where is the...? (¿Dónde está...?), What time is it? (¿Qué hora es?). Para dar información: It is on the left/right (Está a la izquierda/derecha), Go straight (Siga recto), Turn left/right (Gire a la izquierda/derecha).',palabras_clave:['ask','information','can you tell me','where is','what time','left','right','straight','turn','help']},
    {id:'ing_g4_029',grado:4,tema:'famous historical figures',pregunta:'¿Cómo hablo de personajes históricos en inglés?',respuesta:'Historical figures vocabulary: He was born in... (Nació en...), He/She lived in... (Vivió en...), He/She invented... (Inventó...). Examples: Simon Bolivar was born in 1783 in Venezuela. He was the Liberator of South America. Marie Curie was a scientist. She discovered radium. Nelson Mandela fought for freedom in South Africa.',palabras_clave:['historical','figure','born','lived','invented','discovered','Bolivar','Curie','Mandela','scientist']},
    {id:'ing_g4_030',grado:4,tema:'environment conservation',pregunta:'¿Cómo hablo del medio ambiente y la conservación en inglés?',respuesta:'Environment vocabulary: pollution (contaminación), recycle (reciclar), renewable energy (energía renovable), endangered species (especie en peligro), deforestation (deforestación), climate change (cambio climático), protect (proteger), save water (ahorrar agua). We must protect the environment. Reduce, reuse, recycle.',palabras_clave:['environment','pollution','recycle','renewable','endangered','deforestation','climate','protect','save water']},
    {id:'ing_g4_031',grado:4,tema:'food and nutrition',pregunta:'¿Cómo hablo de comida y nutrición en inglés?',respuesta:'Food groups: fruits (frutas), vegetables (verduras), grains (cereales), proteins (proteínas), dairy (lácteos). Healthy food: apples, carrots, rice, chicken, milk. Junk food: chips, soda, candy. Phrases: I eat breakfast/lunch/dinner. My favorite food is... I am allergic to... Eating vegetables is good for your health.',palabras_clave:['food','fruit','vegetable','grain','protein','dairy','healthy','junk food','breakfast','lunch','dinner']},
    {id:'ing_g4_032',grado:4,tema:'connectors',pregunta:'¿Qué conectores importantes debo conocer en inglés?',respuesta:'Connectors in English: AND (y) joins ideas. BUT (pero) contrasts. BECAUSE (porque) gives a reason. SO (entonces) gives a result. ALTHOUGH / EVEN THOUGH (aunque) concedes. HOWEVER (sin embargo) contrasts. FIRST, THEN, FINALLY (primero, luego, finalmente) for sequence. Example: I like math, but I find it difficult.',palabras_clave:['connector','and','but','because','so','although','however','first','then','finally','discourse']},
    {id:'ing_g4_033',grado:4,tema:'writing informal messages',pregunta:'¿Cómo escribo un mensaje informal en inglés?',respuesta:'An informal message (text or email to a friend) uses casual language. Structure: Greeting (Hi! / Hey!), Body (share news, ask questions), Closing (Take care! / See you soon! / Bye!). Contractions are OK: I am → I\'m, Do not → Don\'t. Example: Hi Ana! How are you? I am having a great time here in Medellín. Talk soon!',palabras_clave:['informal','message','email','greeting','closing','contractions','casual','friend','hi','bye']},
    {id:'ing_g4_034',grado:4,tema:'modal verbs',pregunta:'¿Cómo uso can, must, should en inglés?',respuesta:'Modal verbs: CAN = habilidad o permiso (I can swim / Can I go?). MUST = obligación fuerte (You must study). SHOULD = recomendación (You should eat vegetables). COULD = posibilidad o permiso cortés (Could I use the phone?). No usan "to" después y no cambian con la persona: He can, She must, They should.',palabras_clave:['modal','can','must','should','could','ability','obligation','recommendation','permission','habilidad']},

    // GRADO 5
    {id:'ing_g5_033',grado:5,tema:'present perfect',pregunta:'¿Cómo uso el Present Perfect en inglés?',respuesta:'El Present Perfect conecta el pasado con el presente. Forma: have/has + participio pasado. Se usa para: experiencias (I have visited London), acciones recientes (She has just arrived), acciones que empezaron antes y siguen (I have lived here for 5 years). Palabras clave: just, already, yet, ever, never, since, for.',palabras_clave:['present perfect','have','has','participle','already','just','yet','ever','never','since','for']},
    {id:'ing_g5_034',grado:5,tema:'conditional sentences',pregunta:'¿Qué es el condicional en inglés y cómo lo uso?',respuesta:'Conditional sentences: Zero conditional (hechos): If you heat water, it boils. First conditional (probable): If it rains, I will stay home. Second conditional (hipotético): If I were a bird, I would fly. Third conditional (pasado irreal): If I had studied, I would have passed. Estructura clave: if + condición, resultado.',palabras_clave:['conditional','if','will','would','unreal','hypothetical','zero','first','second','third']},
    {id:'ing_g5_035',grado:5,tema:'passive voice',pregunta:'¿Cómo funciona la voz pasiva en inglés?',respuesta:'La voz pasiva pone énfasis en la acción, no en quien la hace. Forma: objeto + to be + participio pasado (+ by + agente). Ejemplos: Active: The teacher explains the lesson. Passive: The lesson is explained by the teacher. Active: They built the bridge in 1990. Passive: The bridge was built in 1990.',palabras_clave:['passive voice','voz pasiva','is','was','were','been','by','participio','agente','acción']},
    {id:'ing_g5_036',grado:5,tema:'reported speech',pregunta:'¿Qué es el estilo indirecto (reported speech) en inglés?',respuesta:'Reported speech reporta lo que alguien dijo, cambiando el tiempo verbal. Direct: She said, "I am happy." Reported: She said (that) she was happy. Cambios de tiempo: am/is → was, are → were, will → would, can → could. Los pronombres también cambian: I → she/he. Se usa con verbos como said, told, asked, mentioned.',palabras_clave:['reported speech','indirect','said','told','asked','tense shift','pronoun change','that']},
    {id:'ing_g5_037',grado:5,tema:'science vocabulary english',pregunta:'¿Cómo hablo de ciencias en inglés?',respuesta:'Science vocabulary: hypothesis (hipótesis), experiment (experimento), observation (observación), conclusion (conclusión), variable (variable), result (resultado), evidence (evidencia). Scientific method: Ask a question → make a hypothesis → conduct an experiment → analyze results → draw conclusions. Useful: I observed that... / The results show that...',palabras_clave:['science','hypothesis','experiment','observation','conclusion','variable','result','evidence','method']},
    {id:'ing_g5_038',grado:5,tema:'formal writing email',pregunta:'¿Cómo escribo una carta formal en inglés?',respuesta:'Formal email/letter structure: 1) Opening: Dear Mr./Ms. [surname], 2) Reason: I am writing to... / I would like to... 3) Body: formal vocabulary, no contractions. 4) Closing: Yours sincerely (if you know the name) or Yours faithfully (if unknown). 5) Signature. Avoid: slang, contractions, casual expressions.',palabras_clave:['formal','letter','email','dear','sincerely','faithfully','professional','writing','structure']},
    {id:'ing_g5_039',grado:5,tema:'argumentative text english',pregunta:'¿Cómo escribo un texto argumentativo en inglés?',respuesta:'Argumentative text structure: 1) Introduction with thesis: In my opinion... / I believe that... 2) Body paragraphs with arguments: First of all... / Furthermore... / In addition... 3) Counter-argument and refutation: Although some people think... , in fact... 4) Conclusion: In conclusion... / To sum up... / Therefore...',palabras_clave:['argumentative','thesis','argument','in my opinion','furthermore','in addition','conclusion','therefore']},
    {id:'ing_g5_040',grado:5,tema:'Colombia in english advanced',pregunta:'¿Cómo describo Colombia y su cultura en inglés?',respuesta:'Colombia is a country in South America. Its capital is Bogotá. It has 32 departments (departamentos). Colombia is known for its biodiversity, coffee, flowers and music (cumbia, vallenato). The currency is the Colombian peso. Famous Colombians include Gabriel García Márquez (Nobel Prize in Literature) and Shakira. The official language is Spanish.',palabras_clave:['Colombia','Bogotá','biodiversity','coffee','cumbia','vallenato','García Márquez','Shakira','South America']},
    {id:'ing_g5_041',grado:5,tema:'human rights english',pregunta:'¿Cómo hablo de derechos humanos en inglés?',respuesta:'Human rights vocabulary: right (derecho), freedom (libertad), equality (igualdad), justice (justicia), education (educación), health (salud), peace (paz), discrimination (discriminación), protection (protección), citizen (ciudadano). All people have the right to education and health. We must fight against discrimination.',palabras_clave:['human rights','right','freedom','equality','justice','education','health','peace','discrimination','citizen']},
    {id:'ing_g5_042',grado:5,tema:'oral presentation english',pregunta:'¿Cómo hago una buena presentación oral en inglés?',respuesta:'Tips for an oral presentation: 1) Start with a greeting: Good morning everyone, my name is... 2) State your topic: Today I will talk about... 3) Use signal words: First, Next, Then, Finally. 4) Speak clearly, do not rush. 5) Use eye contact. 6) Conclude: In conclusion... / Thank you for listening. 7) Invite questions: Any questions?',palabras_clave:['presentation','oral','greeting','today I will talk','first','next','finally','conclusion','thank you','eye contact']}
  ];
  data.contenido.push(...nuevas);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log('ingles.json OK. Total:', data.contenido.length);
}

// ─── CIENCIAS ────────────────────────────────────────────────────────────────
{
  const path = 'rag_api/knowledge_base/ciencias.json';
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  const nuevas = [
    // GRADO 3
    {id:'cie_g3_044',grado:3,tema:'ciclo del nitrógeno',pregunta:'¿Qué es el ciclo del nitrógeno y por qué es importante?',respuesta:'El nitrógeno es un gas que forma el 78% del aire. Las plantas necesitan nitrógeno para crecer, pero no pueden tomarlo directamente del aire. Unas bacterias especiales que viven en el suelo convierten el nitrógeno del aire en una forma que las plantas pueden usar. Cuando los seres vivos mueren, el nitrógeno regresa al suelo y al aire, completando el ciclo.',palabras_clave:['nitrógeno','ciclo','bacteria','suelo','planta','aire','nutriente','descomposición']},
    {id:'cie_g3_045',grado:3,tema:'propiedades de los materiales',pregunta:'¿Cuáles son las propiedades de los materiales que nos rodean?',respuesta:'Los materiales tienen propiedades que los hacen diferentes: COLOR (rojo, azul, transparente), TEXTURA (liso, rugoso, blando, duro), DUREZA (el diamante es muy duro, la cera es blanda), FLEXIBILIDAD (el plástico dobla, la madera no), CONDUCTIVIDAD (los metales conducen calor y electricidad; la madera no). Conocer estas propiedades ayuda a elegir el material adecuado para cada uso.',palabras_clave:['materiales','propiedades','color','textura','dureza','flexibilidad','conductividad','metal','madera','plástico']},
    {id:'cie_g3_046',grado:3,tema:'vertebrados e invertebrados',pregunta:'¿Cuál es la diferencia entre animales vertebrados e invertebrados?',respuesta:'Los animales VERTEBRADOS tienen columna vertebral (espina dorsal). Se dividen en: peces, anfibios, reptiles, aves y mamíferos. Ejemplos: rana, paloma, delfín, serpiente. Los INVERTEBRADOS no tienen columna vertebral. Son la mayoría de los animales: insectos (abeja, mariposa), arácnidos (araña), gusanos, moluscos (caracol) y crustáceos (cangrejo).',palabras_clave:['vertebrado','invertebrado','columna vertebral','pez','anfibio','reptil','ave','mamífero','insecto','arácnido']},
    {id:'cie_g3_047',grado:3,tema:'fotosíntesis paso a paso',pregunta:'¿Cómo ocurre la fotosíntesis paso a paso?',respuesta:'La fotosíntesis es el proceso con el que las plantas producen su alimento. Paso 1: las raíces absorben agua y minerales del suelo. Paso 2: las hojas absorben dióxido de carbono (CO2) del aire por los estomas. Paso 3: la clorofila en las hojas capta la luz solar. Paso 4: con la energía solar, el agua y el CO2 se convierten en glucosa (azúcar) y oxígeno. Fórmula simplificada: agua + CO2 + luz solar → glucosa + oxígeno.',palabras_clave:['fotosíntesis','clorofila','glucosa','oxígeno','dióxido de carbono','luz','agua','raíz','hoja','estoma']},
    {id:'cie_g3_048',grado:3,tema:'mezclas separación',pregunta:'¿Cómo se separan las mezclas?',respuesta:'Las mezclas se pueden separar porque sus componentes no se unen químicamente. Métodos: FILTRACIÓN separa sólidos de líquidos (colar el café). EVAPORACIÓN separa sal del agua (calentar hasta que el agua se evapore). DECANTACIÓN separa líquidos de diferente densidad (aceite y agua). IMANTACIÓN separa metales con un imán (arena y limaduras de hierro). En casa usamos estos métodos todos los días.',palabras_clave:['mezcla','separar','filtración','evaporación','decantación','imantación','sólido','líquido','sal','agua']},
    {id:'cie_g3_049',grado:3,tema:'agua potable',pregunta:'¿Cómo se purifica el agua para que sea potable?',respuesta:'El agua potable es la que podemos tomar sin enfermarnos. Para purificarla: 1) COAGULACIÓN: se agregan sustancias que juntan las partículas sucias. 2) SEDIMENTACIÓN: las partículas caen al fondo. 3) FILTRACIÓN: pasa por capas de arena y grava. 4) CLORACIÓN: se añade cloro para eliminar bacterias. En casa podemos hervir el agua o usar filtros. En Colombia EPM trata el agua de Medellín.',palabras_clave:['agua potable','purificación','filtración','cloración','sedimentación','limpia','bacteria','EPM','Medellín','hervir']},
    {id:'cie_g3_050',grado:3,tema:'energía solar',pregunta:'¿Qué es la energía solar y cómo la usamos?',respuesta:'La energía solar es la energía que llega del sol en forma de luz y calor. Es RENOVABLE porque no se agota. Usos: paneles solares convierten la luz en electricidad para casas y edificios. Calentadores solares calientan el agua. Las plantas la usan en la fotosíntesis. Colombia tiene mucho sol, especialmente en regiones como el Caribe y los Llanos, lo que la hace ideal para el uso solar.',palabras_clave:['energía solar','renovable','panel solar','electricidad','calor','luz','fotosíntesis','Colombia','sostenible']},
    {id:'cie_g3_051',grado:3,tema:'sistema solar básico g3',pregunta:'¿Cuántos planetas tiene el sistema solar y cuáles son?',respuesta:'El sistema solar tiene 8 planetas que giran alrededor del sol. En orden desde el sol: 1. Mercurio (el más cercano y pequeño), 2. Venus, 3. Tierra (nuestro hogar), 4. Marte (el planeta rojo), 5. Júpiter (el más grande), 6. Saturno (con anillos), 7. Urano, 8. Neptuno (el más lejano). Plutón ya no se considera planeta, es un planeta enano.',palabras_clave:['sistema solar','planeta','sol','Mercurio','Venus','Tierra','Marte','Júpiter','Saturno','Urano','Neptuno']},
    {id:'cie_g3_052',grado:3,tema:'ciclo de vida de los animales',pregunta:'¿Qué es el ciclo de vida de un animal?',respuesta:'El ciclo de vida muestra las etapas de desarrollo de un ser vivo desde que nace hasta que muere. La rana: huevo → renacuajo → rana adulta. La mariposa: huevo → larva (oruga) → pupa (crisálida) → mariposa adulta (metamorfosis completa). El perro: cachorro → adulto (sin metamorfosis, solo crecimiento). Todos los seres vivos nacen, crecen, se reproducen y mueren.',palabras_clave:['ciclo de vida','etapa','desarrollo','rana','mariposa','metamorfosis','huevo','larva','pupa','adulto','crecimiento']},
    {id:'cie_g3_053',grado:3,tema:'suelo tipos',pregunta:'¿Cuáles son los tipos de suelo y para qué sirve cada uno?',respuesta:'El suelo tiene capas: CAPA SUPERFICIAL (humus, rica en nutrientes, donde crecen las plantas), SUBSUELO (menos nutrientes, raíces profundas llegan aquí), ROCA MADRE (roca sólida debajo). Tipos de suelo: ARCILLOSO (retiene mucha agua, se agrieta al secarse, bueno para cerámica), ARENOSO (drena rápido, poca retención), LIMOSO (el más fértil para agricultura). En Antioquia hay suelos muy fértiles.',palabras_clave:['suelo','arcilloso','arenoso','limoso','humus','nutriente','fértil','capa','raíz','agricultura']},

    // GRADO 4
    {id:'cie_g4_043',grado:4,tema:'sistema inmunológico',pregunta:'¿Cómo funciona el sistema inmunológico del cuerpo?',respuesta:'El sistema inmunológico es la defensa natural del cuerpo contra enfermedades. Sus componentes: GLÓBULOS BLANCOS (leucocitos) que identifican y destruyen gérmenes. ANTICUERPOS: proteínas que neutralizan virus y bacterias específicos. Cuando te vacunas, el sistema aprende a reconocer un germen sin que te enfermes gravemente. La fiebre es una respuesta inmune que crea condiciones desfavorables para los gérmenes.',palabras_clave:['sistema inmunológico','defensa','leucocito','glóbulo blanco','anticuerpo','vacuna','bacteria','virus','fiebre']},
    {id:'cie_g4_044',grado:4,tema:'propiedades de la luz',pregunta:'¿Cuáles son las propiedades de la luz: reflexión y refracción?',respuesta:'La luz viaja en línea recta a 300.000 km/s. REFLEXIÓN: cuando la luz rebota en una superficie (espejo, agua). Por eso nos vemos en el espejo. REFRACCIÓN: cuando la luz cambia de velocidad al pasar de un medio a otro (agua, vidrio) y se dobla. Por eso un lápiz parece doblado dentro de un vaso de agua. Los arcoíris se forman por refracción y dispersión en las gotas de lluvia.',palabras_clave:['luz','reflexión','refracción','espejo','arcoíris','velocidad','medio','agua','lápiz','rebotar']},
    {id:'cie_g4_045',grado:4,tema:'ciclo del carbono',pregunta:'¿Qué es el ciclo del carbono y por qué es importante?',respuesta:'El carbono es un elemento esencial para la vida. El ciclo del carbono: las plantas absorben CO2 del aire en la fotosíntesis. Los animales comen plantas y obtienen carbono. Al respirar, todos liberamos CO2. Al morir, los organismos se descomponen liberando carbono al suelo. La quema de combustibles fósiles (gasolina, carbón) libera CO2 extra, causando el efecto invernadero y el cambio climático.',palabras_clave:['carbono','ciclo','CO2','fotosíntesis','respiración','combustible fósil','efecto invernadero','cambio climático']},
    {id:'cie_g4_046',grado:4,tema:'energía potencial y cinética',pregunta:'¿Qué diferencia hay entre energía potencial y energía cinética?',respuesta:'La ENERGÍA POTENCIAL es la que tiene un objeto por su posición o estado (una roca en lo alto de una montaña, un resorte comprimido). La ENERGÍA CINÉTICA es la energía del movimiento (la roca cayendo, un carro en marcha). Cuando la roca cae, la energía potencial se convierte en cinética. La suma de ambas se llama energía mecánica y se conserva (no se crea ni destruye, solo se transforma).',palabras_clave:['energía','potencial','cinética','mecánica','movimiento','posición','transformar','conservar','roca','resorte']},
    {id:'cie_g4_047',grado:4,tema:'recursos naturales renovables',pregunta:'¿Cuáles son los recursos naturales renovables y no renovables de Colombia?',respuesta:'Los recursos RENOVABLES se reponen naturalmente: agua (ríos, lluvias), energía solar, viento, bosques (si se cuidan), suelo fértil. Los NO RENOVABLES se agotan: petróleo, carbón, gas natural, minerales (oro, esmeraldas). Colombia es rico en ambos: tiene el río Magdalena, páramos que dan agua, petróleo en los Llanos y minería de carbón en el Cesar. Debemos usarlos de forma sostenible.',palabras_clave:['recurso natural','renovable','no renovable','petróleo','carbón','agua','bosque','solar','minería','Colombia','sostenible']},
    {id:'cie_g4_048',grado:4,tema:'sistema nervioso g4',pregunta:'¿Cómo funciona el sistema nervioso?',respuesta:'El sistema nervioso controla todas las funciones del cuerpo. Partes: CEREBRO (controla el pensamiento, emociones y movimientos voluntarios), CEREBELO (coordina el equilibrio y movimientos finos), TALLO ENCEFÁLICO (controla funciones automáticas: respirar, latir el corazón), MÉDULA ESPINAL (conecta el cerebro con el resto del cuerpo). Los NERVIOS llevan mensajes eléctricos por todo el cuerpo a gran velocidad.',palabras_clave:['sistema nervioso','cerebro','cerebelo','médula espinal','nervio','impulso','eléctrico','automático','voluntario']},
    {id:'cie_g4_049',grado:4,tema:'magnetismo',pregunta:'¿Qué es el magnetismo y cómo funciona un imán?',respuesta:'El magnetismo es una fuerza que atrae o repele ciertos materiales (hierro, níquel, cobalto). Un imán tiene dos polos: Norte (N) y Sur (S). Polos iguales se repelen (N-N o S-S). Polos opuestos se atraen (N-S). La Tierra actúa como un gran imán, lo que hace funcionar la brújula. Las aplicaciones del magnetismo incluyen motores eléctricos, parlantes, MRI hospitalarios y tarjetas de crédito.',palabras_clave:['magnetismo','imán','polo norte','polo sur','atraer','repeler','brújula','Tierra','motor eléctrico','hierro']},
    {id:'cie_g4_050',grado:4,tema:'cambios físicos y químicos g4',pregunta:'¿Cuál es la diferencia entre un cambio físico y uno químico?',respuesta:'Un CAMBIO FÍSICO altera la forma o estado del material pero NO cambia su composición química. Ejemplos: romper un papel, derretir hielo, cortar una manzana. El material sigue siendo el mismo. Un CAMBIO QUÍMICO forma una sustancia nueva con propiedades diferentes. Indicios: cambio de color, producción de gas, luz, calor, precipitado. Ejemplos: quemar madera, oxidar hierro (óxido), fermentar el pan (levadura).',palabras_clave:['cambio físico','cambio químico','composición','estado','derretir','quemar','oxidar','nuevo','sustancia','materia']},
    {id:'cie_g4_051',grado:4,tema:'estrella versus planeta',pregunta:'¿En qué se diferencian una estrella y un planeta?',respuesta:'Las ESTRELLAS son esferas de gas (hidrógeno y helio) que producen su propia luz y calor a través de la fusión nuclear. El Sol es una estrella. Hay billones de estrellas en el universo. Los PLANETAS giran alrededor de una estrella, no producen luz propia (reflejan la de su estrella), son más pequeños que las estrellas y pueden ser rocosos (Tierra, Marte) o gaseosos (Júpiter, Saturno).',palabras_clave:['estrella','planeta','sol','luz','fusión nuclear','órbita','rocoso','gaseoso','universo','girar']},
    {id:'cie_g4_052',grado:4,tema:'salud y enfermedades prevención',pregunta:'¿Cómo prevenimos las enfermedades más comunes en Colombia?',respuesta:'Enfermedades comunes y su prevención: DENGUE y MALARIA: eliminar aguas estancadas donde se crían mosquitos. GRIPA: lavarse las manos, cubrirse al estornudar. DIARREA: tomar agua limpia, lavar frutas y verduras. COVID y otras virales: vacunación. CARIES: cepillarse los dientes 3 veces al día. PARASITOSIS: desparasitar con medicamento cada 6 meses. El PAI (Plan Ampliado de Inmunización) ofrece vacunas gratuitas en Colombia.',palabras_clave:['prevención','enfermedad','dengue','malaria','gripa','diarrea','vacuna','higiene','Colombia','PAI','salud']},

    // GRADO 5
    {id:'cie_g5_043',grado:5,tema:'célula eucariota y procariota',pregunta:'¿Cuál es la diferencia entre la célula eucariota y la procariota?',respuesta:'Las células PROCARIOTAS son las más simples: NO tienen núcleo definido, su material genético está libre en el citoplasma. Son las bacterias. Son muy pequeñas (1-10 micrometros). Las células EUCARIOTAS SÍ tienen núcleo con membrana nuclear que protege el ADN. Son más complejas y grandes. Todos los animales, plantas y hongos tienen células eucariotas. Las eucariotas también tienen organelos como mitocondrias y ribosomas.',palabras_clave:['eucariota','procariota','célula','núcleo','ADN','bacteria','organelo','mitocondria','membrana','material genético']},
    {id:'cie_g5_044',grado:5,tema:'ADN herencia',pregunta:'¿Qué es el ADN y cómo determina las características hereditarias?',respuesta:'El ADN (Ácido Desoxirribonucleico) es la molécula que contiene las instrucciones genéticas de un ser vivo. Está en el núcleo de cada célula formando los cromosomas. Los genes son segmentos de ADN que determinan características como el color de ojos, el grupo sanguíneo o la estatura. Heredamos la mitad del ADN de la madre y la mitad del padre, lo que explica el parecido familiar.',palabras_clave:['ADN','gen','cromosoma','herencia','características','núcleo','molécula','padre','madre','proteína']},
    {id:'cie_g5_045',grado:5,tema:'cambio climático Colombia',pregunta:'¿Cómo afecta el cambio climático a Colombia?',respuesta:'El cambio climático en Colombia se manifiesta en: DERRETIMIENTO de glaciares (el nevado del Ruiz ha perdido el 90% de su hielo). CAMBIOS EN LLUVIAS: sequías más largas y lluvias más intensas (fenómeno El Niño y La Niña más extremos). AFECTACIÓN DE ECOSISTEMAS: páramos y manglares en riesgo. PÉRDIDA DE BIODIVERSIDAD. Colombia es uno de los países más vulnerables pero también el primero en biodiversidad en proporción a su territorio.',palabras_clave:['cambio climático','Colombia','glaciar','nevado del Ruiz','páramo','biodiversidad','El Niño','La Niña','sequía','lluvia']},
    {id:'cie_g5_046',grado:5,tema:'sistemas del cuerpo integración',pregunta:'¿Cómo trabajan juntos los sistemas del cuerpo humano?',respuesta:'Los sistemas del cuerpo están interconectados. Ejemplo de integración: cuando corres, el MUSCULAR usa energía → el DIGESTIVO descompone alimentos → el CIRCULATORIO lleva nutrientes y oxígeno a los músculos → el RESPIRATORIO aumenta la entrada de O2 y salida de CO2 → el NERVIOSO coordina todo el movimiento → el EXCRETOR elimina los desechos. La salud de uno afecta a todos los demás.',palabras_clave:['sistemas del cuerpo','muscular','digestivo','circulatorio','respiratorio','nervioso','excretor','integración','oxígeno']},
    {id:'cie_g5_047',grado:5,tema:'átomo y molécula g5',pregunta:'¿Qué es un átomo y una molécula?',respuesta:'El ÁTOMO es la partícula más pequeña de un elemento que conserva sus propiedades químicas. Tiene: núcleo (protones +, neutrones 0) y electrones (-) girando alrededor. Una MOLÉCULA es la unión de dos o más átomos. Ejemplo: el agua (H2O) = 2 átomos de hidrógeno + 1 de oxígeno. El oxígeno del aire es O2 (2 átomos de oxígeno unidos). Hay más de 100 elementos en la tabla periódica.',palabras_clave:['átomo','molécula','protón','neutrón','electrón','núcleo','hidrógeno','oxígeno','H2O','elemento','tabla periódica']},
    {id:'cie_g5_048',grado:5,tema:'energías renovables Colombia',pregunta:'¿Qué energías renovables se usan en Colombia?',respuesta:'Colombia genera el 70% de su electricidad con energía HIDRÁULICA (agua de ríos y embalses como Ituango e Hidroituango en Antioquia). Otras renovables: SOLAR: paneles en Guajira (la más soleada). EÓLICA: parques de molinos de viento en La Guajira (Jepírachi). GEOTÉRMICA: calor del subsuelo volcánico. BIOMASA: residuos de caña de azúcar. Colombia quiere llegar al 100% de energía limpia para 2040.',palabras_clave:['energía renovable','hidráulica','solar','eólica','biomasa','Colombia','Guajira','Ituango','limpia','sostenible']},
    {id:'cie_g5_049',grado:5,tema:'microorganismos beneficios',pregunta:'¿Qué son los microorganismos y para qué sirven?',respuesta:'Los microorganismos son seres vivos microscópicos: BACTERIAS (descomponen materia orgánica, algunas nos enferman, otras como el yogurt son beneficiosas), VIRUS (solo se reproducen dentro de células vivas, causan gripa, COVID), HONGOS microscópicos (levaduras en el pan y la cerveza, algunos antibióticos vienen de hongos como la penicilina), ALGAS y PROTOZOOS. Son fundamentales para los ciclos biogeoquímicos.',palabras_clave:['microorganismo','bacteria','virus','hongo','levadura','yogurt','penicilina','microscópico','beneficioso','descomponer']},
    {id:'cie_g5_050',grado:5,tema:'biotecnología básica',pregunta:'¿Qué es la biotecnología y cómo nos ayuda?',respuesta:'La biotecnología usa seres vivos o sus procesos para desarrollar productos útiles. Ejemplos: ALIMENTOS: yogurt, queso y pan usan bacterias y levaduras. MEDICINA: insulina producida por bacterias modificadas genéticamente para tratar la diabetes. AGRICULTURA: plantas resistentes a plagas (GMO). VACUNAS: preparadas con partes de virus o bacterias. BIOCOMBUSTIBLES: combustible hecho de plantas. Es una de las ciencias del futuro.',palabras_clave:['biotecnología','bacteria','levadura','insulina','vacuna','genético','GMO','queso','biocombustible','medicamento']},
    {id:'cie_g5_051',grado:5,tema:'biodiversidad amenazas',pregunta:'¿Por qué está en peligro la biodiversidad en Colombia y cómo la protegemos?',respuesta:'Colombia es el segundo país más biodiverso del mundo. Amenazas: DEFORESTACIÓN para cultivos ilegales y ganadería (se pierde el 1% de bosques anuales). CONTAMINACIÓN de ríos y suelos. CAZA y tráfico de especies. CAMBIO CLIMÁTICO altera hábitats. Protección: Parques Nacionales Naturales (59 en Colombia), leyes ambientales, reforestación, educación ambiental. Todos podemos ayudar: reducir, reutilizar, reciclar.',palabras_clave:['biodiversidad','deforestación','Colombia','caza','contaminación','parque nacional','reforestación','proteger','amenaza','especie']},
    {id:'cie_g5_052',grado:5,tema:'circuito eléctrico básico',pregunta:'¿Cómo funciona un circuito eléctrico?',respuesta:'Un circuito eléctrico es el camino que recorre la corriente eléctrica. Componentes básicos: FUENTE DE ENERGÍA (pila o batería), CONDUCTORES (cables de cobre), RECEPTOR (bombillo, motor), INTERRUPTOR (para abrir o cerrar el circuito). En circuito SERIE los componentes van uno tras otro; si uno falla, todos se apagan. En circuito PARALELO cada componente tiene su propia rama; si uno falla, los demás siguen funcionando.',palabras_clave:['circuito eléctrico','corriente','pila','batería','conductor','bombillo','interruptor','serie','paralelo','cable']}
  ];
  data.contenido.push(...nuevas);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log('ciencias.json OK. Total:', data.contenido.length);
}

// ─── SOCIALES ────────────────────────────────────────────────────────────────
{
  const path = 'rag_api/knowledge_base/sociales.json';
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  const nuevas = [
    // GRADO 3
    {id:'soc_g3_041',grado:3,tema:'vereda y municipio',pregunta:'¿Qué es una vereda y cómo se organiza un municipio en Colombia?',respuesta:'La VEREDA es la división más pequeña del campo en Colombia; es una comunidad rural con pocas familias. El MUNICIPIO agrupa varias veredas y barrios urbanos; tiene un alcalde y un concejo. En Antioquia hay 125 municipios. El CORREGIMIENTO es una zona rural que depende del municipio. Medellín tiene 5 corregimientos: Palmitas, San Cristóbal, Altavista, San Antonio de Prado y Santa Elena.',palabras_clave:['vereda','municipio','corregimiento','alcalde','concejo','rural','Antioquia','Medellín','organización','territorio']},
    {id:'soc_g3_042',grado:3,tema:'servicios públicos',pregunta:'¿Qué son los servicios públicos y cuáles hay en Colombia?',respuesta:'Los servicios públicos son servicios esenciales que el Estado garantiza a los ciudadanos. En Colombia incluyen: AGUA POTABLE Y ALCANTARILLADO (EPM en Medellín), ENERGÍA ELÉCTRICA, GAS NATURAL, INTERNET Y TELEFONÍA, RECOLECCIÓN DE BASURAS. Son pagados mensualmente con recibos. El acceso a agua limpia y energía es un derecho fundamental. En zonas rurales algunos servicios aún son limitados.',palabras_clave:['servicio público','agua','electricidad','gas','internet','alcantarillado','EPM','Colombia','derecho','recibo']},
    {id:'soc_g3_043',grado:3,tema:'culturas afrocolombianas',pregunta:'¿Quiénes son los pueblos afrocolombianos y dónde viven?',respuesta:'Los afrocolombianos son descendientes de personas africanas traídas a América durante la colonización española (siglos XVI-XIX). Son el 10% de la población colombiana. Se concentran en: Chocó (el departamento con mayor población afrocolombiana), el Caribe (Cartagena, Barranquilla), Valle del Cauca y Urabá en Antioquia. Su cultura es rica en música (currulao, champeta, mapalé), gastronomía y tradiciones orales. La Ley 70 de 1993 reconoce sus derechos.',palabras_clave:['afrocolombiano','Chocó','Cartagena','cultura','música','currulao','África','colonización','derechos','ley 70']},
    {id:'soc_g3_044',grado:3,tema:'la Amazonia colombiana',pregunta:'¿Por qué es importante la Amazonia colombiana?',respuesta:'La Amazonia colombiana ocupa el 35% del territorio nacional (Amazonas, Putumayo, Caquetá, Vaupés, Guainía). Es el "pulmón del mundo" porque sus árboles absorben CO2 y producen oxígeno. Alberga miles de especies de animales y plantas únicas. Allí viven comunidades indígenas como los Tikuna, Huitoto y Cubeo. El río Amazonas nace cerca de Colombia y es el río de mayor caudal del mundo. La deforestación es su mayor amenaza.',palabras_clave:['Amazonia','Colombia','selva','pulmón','biodiversidad','indígena','Tikuna','río Amazonas','Putumayo','deforestación']},
    {id:'soc_g3_045',grado:3,tema:'Carnaval de Barranquilla',pregunta:'¿Qué es el Carnaval de Barranquilla y por qué es patrimonio?',respuesta:'El Carnaval de Barranquilla es una fiesta popular que se celebra cada año antes de la Cuaresma (febrero o marzo) y dura 4 días. Fue declarado Patrimonio Cultural Inmaterial de la Humanidad por la UNESCO en 2003. Incluye desfiles como la Batalla de Flores, comparsas, danzas (cumbia, mapalé, porro), disfraces coloridos y personajes como el Rey Momo y la Reina del Carnaval. Mezcla tradiciones africanas, indígenas y europeas.',palabras_clave:['Carnaval','Barranquilla','UNESCO','patrimonio','cumbia','mapalé','Batalla de Flores','Rey Momo','fiesta','tradición']},
    {id:'soc_g3_046',grado:3,tema:'ciudades principales Colombia',pregunta:'¿Cuáles son las principales ciudades de Colombia y dónde están?',respuesta:'Las principales ciudades de Colombia son: BOGOTÁ (capital, centro del país, 8 millones de habitantes). MEDELLÍN (Antioquia, noroeste, "Ciudad de la Eterna Primavera"). CALI (Valle del Cauca, occidente, capital de la salsa). BARRANQUILLA (Atlántico, costa Caribe). CARTAGENA (Bolívar, costa Caribe, patrimonio histórico). BUCARAMANGA (Santander, nororiente). Todas son capitales de su departamento.',palabras_clave:['ciudad','Colombia','Bogotá','Medellín','Cali','Barranquilla','Cartagena','capital','departamento']},
    {id:'soc_g3_047',grado:3,tema:'medio de transporte Colombia',pregunta:'¿Cuáles son los medios de transporte más importantes en Colombia?',respuesta:'Colombia usa diferentes medios de transporte: TERRESTRE: carreteras (la Troncal de Occidente, la vía al mar), el metro de Medellín, el TransMilenio de Bogotá, el Mío de Cali. AÉREO: aeropuertos internacionales en Bogotá (El Dorado), Medellín (JMC y Olaya Herrera), Cali (Alfonso Bonilla). FLUVIAL: ríos Magdalena, Cauca y Amazonas. FÉRREO: ferrocarriles históricos, tren de Medellín. El metro y el tranvía transformaron a Medellín.',palabras_clave:['transporte','metro','TransMilenio','aeropuerto','río','Magdalena','carretera','Bogotá','Medellín','tren']},
    {id:'soc_g3_048',grado:3,tema:'problemáticas ambientales locales',pregunta:'¿Cuáles son los problemas ambientales de nuestras ciudades y cómo los resolvemos?',respuesta:'Problemas ambientales urbanos en Colombia: CONTAMINACIÓN DEL AIRE: carros y fábricas (Medellín tuvo alerta roja por smog). BASURAS: poco reciclaje, mucha basura en ríos y calles. RUIDO: tráfico y construcciones. FALTA DE ÁRBOLES en barrios. Soluciones ciudadanas: reciclar correctamente, usar transporte público o bicicleta, plantar árboles, denunciar quemas. Programas como "Basura Cero" y "Ciclovía" ayudan en varias ciudades.',palabras_clave:['ambiental','contaminación','aire','basura','reciclaje','ruido','árbol','Medellín','ciudad','solución']},
    {id:'soc_g3_049',grado:3,tema:'regiones naturales Colombia g3',pregunta:'¿Cuáles son las regiones naturales de Colombia?',respuesta:'Colombia tiene 6 regiones naturales: 1. CARIBE: costa norte, clima caliente, playas, ciudades como Cartagena y Barranquilla. 2. PACÍFICO: costa oeste, selva lluviosa, biodiversidad. 3. ANDINA: cordilleras y valles, donde vive la mayoría de colombianos (Bogotá, Medellín, Cali). 4. ORINOQUÍA (Llanos): grandes llanuras, ganadería. 5. AMAZONIA: selva tropical, ríos gigantes. 6. INSULAR: islas San Andrés y Providencia.',palabras_clave:['región','Caribe','Pacífico','Andina','Orinoquía','Amazonia','Insular','Colombia','cordillera','selva']},
    {id:'soc_g3_050',grado:3,tema:'gastronomía colombiana regional',pregunta:'¿Cuáles son los platos típicos de Colombia según la región?',respuesta:'Gastronomía regional: ANDINA: bandeja paisa (frijoles, chicharrón, huevo, arroz, aguacate, chorizo), ajiaco bogotano, mazamorra. CARIBE: sancocho de pescado, arroz con coco, patacón. PACÍFICO: encocado de camarón, arroz atollado. LLANERA: mamona (carne a la llanera). AMAZONIA: pirarucú, ají negro. Las bebidas típicas son el tinto (café negro), la limonada de panela y el jugo de lulo o guanábana.',palabras_clave:['gastronomía','bandeja paisa','ajiaco','sancocho','arroz con coco','mamona','Colombia','regional','comida','plato']},

    // GRADO 4
    {id:'soc_g4_026',grado:4,tema:'independencia Colombia fechas',pregunta:'¿Cuáles son las fechas más importantes de la independencia de Colombia?',respuesta:'Fechas clave: 20 DE JULIO DE 1810: Grito de Independencia en Bogotá (hoy es el día de la independencia). La pelea con el florero de Llorente fue el pretexto. 7 DE AGOSTO DE 1819: Batalla de Boyacá, victoria definitiva de Simón Bolívar y Santander sobre los españoles. 1821: Congreso de Cúcuta, se redacta la primera Constitución de la Gran Colombia. 1830: disolución de la Gran Colombia (Venezuela, Ecuador y Colombia se separan).',palabras_clave:['independencia','20 de julio','1810','Boyacá','Bolívar','Santander','Gran Colombia','1821','Cúcuta','España']},
    {id:'soc_g4_027',grado:4,tema:'El Congreso de Colombia',pregunta:'¿Qué es el Congreso de Colombia y qué hace?',respuesta:'El Congreso de la República es la rama legislativa del gobierno. Hace las leyes. Está compuesto por: SENADO (108 senadores elegidos para 4 años por todo el país) y CÁMARA DE REPRESENTANTES (172 representantes elegidos por departamento). Funciones: crear y reformar leyes, aprobar el presupuesto nacional, controlar al gobierno, aprobar o rechazar tratados internacionales. Sede: Capitolio Nacional en Bogotá.',palabras_clave:['Congreso','Senado','Cámara','representantes','ley','legislativo','gobierno','Colombia','Bogotá','Capitolio']},
    {id:'soc_g4_028',grado:4,tema:'resguardos indígenas',pregunta:'¿Qué son los resguardos indígenas en Colombia?',respuesta:'Los resguardos indígenas son territorios legalmente reconocidos donde los pueblos indígenas pueden vivir según sus costumbres y gobernar sus propios asuntos. Colombia tiene más de 100 pueblos indígenas (Nasa, Wayuu, Embera, Arhuaco, Sikuani). Representan el 4% de la población. La Constitución de 1991 reconoció sus derechos: autonomía, territorio, identidad cultural y educación propia. Los Cabildos son sus autoridades.',palabras_clave:['resguardo','indígena','pueblo','Nasa','Wayuu','Embera','Arhuaco','Constitución 1991','autonomía','cabildo']},
    {id:'soc_g4_029',grado:4,tema:'Colombia en América del Sur',pregunta:'¿Dónde está Colombia en América del Sur y con qué países limita?',respuesta:'Colombia está ubicada en el noroccidente de América del Sur. Limita con: VENEZUELA al oriente, BRASIL al sureste, PERÚ al sur, ECUADOR al suroeste, PANAMÁ al noroccidente. Por el norte y occidente tiene costas en el MAR CARIBE y el OCÉANO PACÍFICO (es el único país de Sudamérica con dos océanos). Comparte el río Amazonas con Perú y Brasil. Capital: Bogotá, ubicada en la cordillera Oriental.',palabras_clave:['Colombia','América del Sur','Venezuela','Brasil','Perú','Ecuador','Panamá','Caribe','Pacífico','límites']},
    {id:'soc_g4_030',grado:4,tema:'turismo Medellín',pregunta:'¿Qué lugares turísticos tiene Medellín y Antioquia?',respuesta:'Medellín: Parque Explora (ciencia), Jardín Botánico, Pueblito Paisa (réplica de pueblo antioqueño), Museo de Antioquia (obras de Botero), El Peñol (piedra gigante en Guatapé), Metro y tranvía. Antioquia: Jardín (uno de los pueblos más bonitos), Santa Fe de Antioquia (patrimonio histórico), Nuquí (playa en el Pacífico), Caño Cristales (no es Antioquia pero sí Colombia). Medellín fue nombrada la ciudad más innovadora del mundo en 2013.',palabras_clave:['Medellín','turismo','Botero','Guatapé','Explora','Jardín Botánico','Antioquia','innovación','Jardín','Pacífico']},
    {id:'soc_g4_031',grado:4,tema:'historia siglo XX Colombia',pregunta:'¿Qué pasó en Colombia durante el siglo XX?',respuesta:'Eventos clave del siglo XX en Colombia: 1899-1902: Guerra de los Mil Días (última gran guerra civil). 1928: Masacre de las Bananeras (trabajadores de United Fruit Company). 1948: Bogotazo y asesinato de Jorge Eliécer Gaitán, inicio de La Violencia. 1953-1957: Dictadura de Gustavo Rojas Pinilla. 1958: Frente Nacional (alternancia Liberal-Conservador). Década de 1960: nacen las guerrillas (FARC, ELN). 1991: Nueva Constitución que reconoce los derechos de todos.',palabras_clave:['siglo XX','Colombia','Bogotazo','Gaitán','Violencia','Rojas Pinilla','Frente Nacional','FARC','Constitución 1991','historia']},
    {id:'soc_g4_032',grado:4,tema:'pisos térmicos Colombia',pregunta:'¿Qué son los pisos térmicos en Colombia?',respuesta:'Los pisos térmicos son zonas de diferente temperatura según la altitud (altura sobre el mar). En Colombia: CÁLIDO: 0-1000 m (costa, Llanos, Amazonia), temperatura >24°C. TEMPLADO: 1000-2000 m (Medellín, eje cafetero), 17-24°C. FRÍO: 2000-3000 m (Bogotá, Manizales), 12-17°C. PÁRAMO: 3000-4500 m (Sumapaz), 0-12°C. GLACIAL: >4500 m (Nevado del Ruiz), por debajo de 0°C. Esta variedad permite cultivar todo tipo de productos.',palabras_clave:['piso térmico','altitud','temperatura','cálido','templado','frío','páramo','glacial','Colombia','cordillera']},
    {id:'soc_g4_033',grado:4,tema:'economía colombiana',pregunta:'¿Cuáles son las principales actividades económicas de Colombia?',respuesta:'Principales actividades económicas: AGRICULTURA: café (Colombia es famoso mundialmente), flores (2do exportador mundial), banano, cacao, azúcar, palma de aceite. MINERÍA: petróleo (principal exportación), carbón (Cerrejón en La Guajira), oro y esmeraldas. INDUSTRIA: textiles, alimentos, bebidas. SERVICIOS: turismo, finanzas, tecnología. GANADERÍA en los Llanos. El café colombiano es reconocido por su calidad y aroma.',palabras_clave:['economía','café','flores','petróleo','carbón','exportación','agricultura','minería','ganadería','Colombia']},
    {id:'soc_g4_034',grado:4,tema:'democracia escolar',pregunta:'¿Cómo funciona la democracia en el colegio?',respuesta:'La democracia escolar permite que los estudiantes participen en las decisiones del colegio. Mecanismos: PERSONERO ESTUDIANTIL: elegido por todos los estudiantes, defiende sus derechos. CONSEJO ESTUDIANTIL: representantes de cada grado. GOBIERNO ESCOLAR: incluye rector, docentes, padres y estudiantes. MANUAL DE CONVIVENCIA: normas acordadas por la comunidad. Votar, respetar la mayoría y proteger las minorías son valores democráticos.',palabras_clave:['democracia','personero','consejo estudiantil','gobierno escolar','votar','representante','colegio','derecho','convivencia']},
    {id:'soc_g4_035',grado:4,tema:'patrimonio cultural inmaterial',pregunta:'¿Qué es el patrimonio cultural inmaterial de Colombia?',respuesta:'El patrimonio cultural inmaterial son las tradiciones, costumbres, saberes y expresiones que una comunidad reconoce como parte de su identidad. Colombia tiene varios declarados por la UNESCO: Carnaval de Barranquilla, Carnaval de Blancos y Negros (Pasto), música vallenata, procesiones de Semana Santa de Popayán. También incluye gastronomía, medicina tradicional, artesanías y lenguas indígenas.',palabras_clave:['patrimonio','cultural','inmaterial','UNESCO','Carnaval','vallenato','tradición','identidad','Popayán','artesanía']},

    // GRADO 5
    {id:'soc_g5_031',grado:5,tema:'Segunda Guerra Mundial Colombia',pregunta:'¿Qué fue la Segunda Guerra Mundial y cómo afectó a Colombia?',respuesta:'La Segunda Guerra Mundial (1939-1945) fue el conflicto bélico más grande de la historia. Participaron las Potencias del Eje (Alemania nazi de Hitler, Italia de Mussolini, Japón) contra los Aliados (EE.UU., URSS, Reino Unido, Francia). Terminó con la derrota del Eje y el uso de la bomba atómica en Japón. Colombia no combatió directamente pero declaró la guerra al Eje en 1943. La guerra provocó 70 millones de muertos y originó la ONU en 1945.',palabras_clave:['Segunda Guerra Mundial','1939','1945','Hitler','Aliados','bomba atómica','ONU','Colombia','nazismo','Japón']},
    {id:'soc_g5_032',grado:5,tema:'derechos económicos sociales culturales',pregunta:'¿Qué son los derechos económicos, sociales y culturales (DESC)?',respuesta:'Los DESC son derechos que garantizan condiciones de vida digna para todos. Incluyen: EDUCACIÓN (el Estado debe garantizar educación gratuita y de calidad), SALUD (atención médica para todos), TRABAJO DIGNO (salario justo), VIVIENDA (hogar adecuado), ALIMENTACIÓN, CULTURA (acceso al arte y la ciencia). La Constitución de 1991 los reconoce. El ICBF defiende los derechos de los niños en Colombia.',palabras_clave:['DESC','derechos','educación','salud','trabajo','vivienda','alimentación','cultura','Constitución','ICBF']},
    {id:'soc_g5_033',grado:5,tema:'TLC Colombia',pregunta:'¿Qué es un Tratado de Libre Comercio (TLC) y cómo afecta a Colombia?',respuesta:'Un TLC es un acuerdo entre dos o más países para reducir o eliminar impuestos a las importaciones y exportaciones entre ellos. Colombia tiene TLC con EE.UU., la Unión Europea, Canadá y otros. Ventajas: más mercados para el café, flores y otros productos colombianos. Desventajas: competencia para agricultores locales que compiten con productos más baratos del exterior. El balance depende de qué tan preparado esté el país para competir.',palabras_clave:['TLC','tratado','libre comercio','importación','exportación','EE.UU.','Europa','Colombia','impuesto','competencia']},
    {id:'soc_g5_034',grado:5,tema:'democracia participativa Colombia',pregunta:'¿Cómo se ejerce la democracia participativa en Colombia?',respuesta:'La democracia participativa permite que los ciudadanos tomen decisiones, no solo votando sino también: REFERÉNDUM: votación sobre una ley o reforma. PLEBISCITO: aprobación de decisión del gobierno (el del proceso de paz de 2016). INICIATIVA LEGISLATIVA POPULAR: los ciudadanos proponen leyes si reúnen firmas. CABILDO ABIERTO: reunión de comunidad para decidir temas locales. REVOCATORIA DEL MANDATO: retirar a un alcalde o gobernador electo si no cumple.',palabras_clave:['democracia participativa','referéndum','plebiscito','iniciativa popular','cabildo abierto','revocatoria','Colombia','ciudadano','paz']},
    {id:'soc_g5_035',grado:5,tema:'ODS objetivos desarrollo sostenible',pregunta:'¿Qué son los Objetivos de Desarrollo Sostenible (ODS)?',respuesta:'Los ODS son 17 metas que los países del mundo acordaron cumplir para 2030, establecidos por la ONU en 2015. Incluyen: fin de la pobreza, hambre cero, salud y bienestar, educación de calidad, igualdad de género, agua limpia, energía limpia, trabajo digno, ciudades sostenibles, acción climática y vida de ecosistemas. Colombia los adoptó y los integra en sus planes de gobierno. Cada ciudadano puede contribuir.',palabras_clave:['ODS','objetivos de desarrollo sostenible','ONU','2030','pobreza','educación','clima','igualdad','Colombia','meta']},
    {id:'soc_g5_036',grado:5,tema:'historia Colombia siglo XIX',pregunta:'¿Qué ocurrió en Colombia durante el siglo XIX después de la independencia?',respuesta:'Tras la independencia (1819), Colombia enfrentó grandes retos: 1830: Disolución de la Gran Colombia (Venezuela, Ecuador y Colombia se separan). Se llamó "Nueva Granada" hasta 1886. Guerras civiles entre Liberales (federalismo, libre comercio) y Conservadores (centralismo, Iglesia). Se redactaron varias constituciones. 1886: Constitución centralista que duró hasta 1991. 1899: Guerra de los Mil Días, la peor guerra civil. 1903: Panamá se separa de Colombia.',palabras_clave:['siglo XIX','independencia','Nueva Granada','Liberales','Conservadores','Constitución 1886','guerra civil','Panamá','Gran Colombia']},
    {id:'soc_g5_037',grado:5,tema:'culturas precolombinas Colombia',pregunta:'¿Cuáles fueron las principales culturas precolombinas de Colombia?',respuesta:'Antes de la llegada de los españoles, Colombia tenía civilizaciones avanzadas: MUISCAS: en el altiplano cundiboyacense, crearon la leyenda de El Dorado, tenían comercio desarrollado y sistema político (confederación de cacicazgos). TAIRONAS: en la Sierra Nevada de Santa Marta, construyeron Ciudad Perdida (conectada por caminos de piedra). CALIMA y TUMACO: grandes orfebres (oro). QUIMBAYAS: en el eje cafetero, famosos por su orfebrería. SINÚES: en el Caribe.',palabras_clave:['precolombino','Muiscas','Taironas','Calima','Quimbayas','Ciudad Perdida','El Dorado','Colombia','indígena','orfebrería']},
    {id:'soc_g5_038',grado:5,tema:'colonización e independencia',pregunta:'¿Cómo fue el proceso de colonización española y luego la independencia?',respuesta:'COLONIZACIÓN (1492-1810): España llegó a América buscando riqueza. En Colombia fundaron ciudades (Santa Marta 1525, Cartagena 1533, Bogotá 1538). Esclavizaron indígenas y africanos para explotar minas y haciendas. Se formó una sociedad jerárquica: peninsulares, criollos, mestizos, indígenas y esclavos. Los CRIOLLOS (hijos de españoles nacidos en América), educados en ideas ilustradas y liberales, lideraron la independencia.',palabras_clave:['colonización','España','criollo','mestizo','indígena','esclavo','independencia','Santa Marta','Cartagena','Bogotá','ilustración']},
    {id:'soc_g5_039',grado:5,tema:'globalización',pregunta:'¿Qué es la globalización y cómo afecta a Colombia?',respuesta:'La globalización es el proceso de interconexión económica, cultural y política entre todos los países del mundo. Efectos positivos en Colombia: acceso a tecnología, más mercados para exportar, intercambio cultural. Efectos negativos: dependencia de mercados externos, pérdida de identidad cultural local, desigualdad. Internet y las redes sociales aceleraron la globalización. Los colombianos consumen productos y cultura de todo el mundo (música, comida, moda) y exportan café, flores y música.',palabras_clave:['globalización','economía','cultura','internet','tecnología','exportar','identidad','Colombia','mundial','interconexión']},
    {id:'soc_g5_040',grado:5,tema:'Latinoamérica civilizaciones clásicas',pregunta:'¿Cuáles fueron las grandes civilizaciones antiguas del mundo?',respuesta:'Las civilizaciones clásicas del mundo: MESOPOTAMIA: primera escritura (cuneiforme), código Hammurabi (Irak actual). EGIPTO: pirámides, escritura jeroglífica, Imperio del Nilo. GRECIA ANTIGUA: democracia, filosofía (Sócrates, Platón, Aristóteles), Juegos Olímpicos. ROMA: derecho romano (base de nuestras leyes), República y luego Imperio. CHINA ANTIGUA: papel, pólvora, Gran Muralla. MAYAS y AZTECAS en América: astronomía, calendario, arquitectura. Todas influyeron en la cultura moderna.',palabras_clave:['civilización','Mesopotamia','Egipto','Grecia','Roma','China','Mayas','Aztecas','antigua','democracia','filosofía']}
  ];
  data.contenido.push(...nuevas);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log('sociales.json OK. Total:', data.contenido.length);
}

console.log('\nTodos los archivos actualizados correctamente.');
